### ISSUE TITLE
Bot does not join channel

### ISSUE THREAD

**Issue by AuguxX** [rivor/fortnite-scrim-bot#3]
(node:4884) DeprecationWarning: Collection#find: pass a function instead
(node:4884) DeprecationWarning: Collection#find: pass a function instead

**Comment by rivor** [comment]
It does join, make sure you have correct !setup settings, just type !setup and it'll tell you what to do. Also that warning is whatsoever not even related to bot not joining, also it's just warning. It has no any affect to bot functionality.
