### ISSUE TITLE
SQLITE error

### ISSUE THREAD

**Issue by UntouchedOdin0** [rivor/fortnite-scrim-bot#6]
I tried to launch the bot how I normally launch node.js bots, but this error appeared. 

node bot.js
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: SQLITE_CANTOPEN: unable to open database file
Emitted 'error' event at:

F:\SOLO SNIPES BOT>pause
Press any key to continue . . .

**Comment by AuguxX** [comment]
same here.
