### ISSUE TITLE
bot doesn't respond to anything 

### ISSUE THREAD

**Issue by DieselGaming** [rivor/fortnite-scrim-bot#7]
cmd stays the same, just blank the bot is online. when I type !setup nothing happens, when I type any command nothing happens. 
cmd:
![image](https://user-images.githubusercontent.com/44411085/48969589-a2f9ae00-eff8-11e8-839d-c6c25a3f9d14.png)
discord:
![image](https://user-images.githubusercontent.com/44411085/48969608-c7ee2100-eff8-11e8-9295-e3d779f8fa4f.png)

**Comment by rivor** [comment]
Stop making these false "issues", everything works fine for me and other people who i've seen that use it.
